pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
    }

    stages {
        stage('Preparar ambiente') {
            steps {
                echo 'Criando ambiente virtual...'
                sh 'python3 -m venv $VENV_DIR'
                sh './$VENV_DIR/bin/pip install --upgrade pip'
            }
        }

        stage('Instalar dependências') {
            steps {
                echo 'Instalando dependências...'
                sh './$VENV_DIR/bin/pip install -r requirements.txt'
            }
        }

        stage('Rodar testes') {
            steps {
                echo 'Executando testes com pytest...'
                sh './$VENV_DIR/bin/pytest'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finalizado.'
        }
        failure {
            echo 'Pipeline falhou!'
        }
    }
}
